import user_global_share

class user_signature_generation_share:
    def __init__(self, generating_user_id : str, target_user_index : int, target_user_evaluation : int, v_is, v0):
        """
        v_i = g^ai - where ai is the coefficient of the shamir polynomial generated by generating user
        v_0 - g^secret
        """
        self.generating_user_id = generating_user_id
        self.target_user_index = target_user_index
        self.target_user_evaluation = target_user_evaluation
        self.g_pow_coeffcients_list = v_is
        self.v0 = v0
        pass

    def generate_global_share_from_users_share(self, all_users_shares : list) -> user_global_share:
